const VIEW_LEVEL_PERMISSION = 'BUSINESS_DETAILS:VIEW'
const AMEND_LEVEL_PERMISSION = 'BUSINESS_DETAILS:AMEND'
const MAKE_LEGAL_CHANGES_PERMISSION = 'BUSINESS_DETAILS:MAKE_LEGAL_CHANGES'
const FULL_PERMISSION = 'BUSINESS_DETAILS:FULL_PERMISSION'

const VIEW_PERMISSIONS = [VIEW_LEVEL_PERMISSION, AMEND_LEVEL_PERMISSION, MAKE_LEGAL_CHANGES_PERMISSION, FULL_PERMISSION]
const AMEND_PERMISSIONS = [AMEND_LEVEL_PERMISSION, MAKE_LEGAL_CHANGES_PERMISSION, FULL_PERMISSION]
const LEGAL_PERMISSIONS = [MAKE_LEGAL_CHANGES_PERMISSION, FULL_PERMISSION]
const FULL_PERMISSIONS = [FULL_PERMISSION]

export {
  VIEW_LEVEL_PERMISSION,
  AMEND_LEVEL_PERMISSION,
  MAKE_LEGAL_CHANGES_PERMISSION,
  FULL_PERMISSION,
  VIEW_PERMISSIONS,
  AMEND_PERMISSIONS,
  LEGAL_PERMISSIONS,
  FULL_PERMISSIONS
}
