const VIEW_LEVEL_PERMISSION = 'LAND_DETAILS:VIEW'
const AMEND_LEVEL_PERMISSION = 'LAND_DETAILS:AMEND'
const SUBMIT_LEVEL_PERMISSION = 'LAND_DETAILS:SUBMIT'
const FULL_PERMISSION = 'LAND_DETAILS:FULL_PERMISSION'

const VIEW_PERMISSIONS = [VIEW_LEVEL_PERMISSION, AMEND_LEVEL_PERMISSION, SUBMIT_LEVEL_PERMISSION, FULL_PERMISSION]
const AMEND_PERMISSIONS = [AMEND_LEVEL_PERMISSION, SUBMIT_LEVEL_PERMISSION, FULL_PERMISSION]
const SUBMIT_PERMISSIONS = [SUBMIT_LEVEL_PERMISSION, FULL_PERMISSION]
const FULL_PERMISSIONS = [FULL_PERMISSION]

export {
  VIEW_LEVEL_PERMISSION,
  AMEND_LEVEL_PERMISSION,
  SUBMIT_LEVEL_PERMISSION,
  FULL_PERMISSION,
  VIEW_PERMISSIONS,
  AMEND_PERMISSIONS,
  SUBMIT_PERMISSIONS,
  FULL_PERMISSIONS
}
